name: Continuous Integration Test Coverage

# Controls when the workflow will run
on: push

jobs:
    
  test_coverage:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'  

      - name: Install dependencies
        run: python3 -m pip install -U pytest pytest-cov

      - name: Generate report log file for milestone 2
        run: (cd tests && ./run_tests.sh pytest --cov-fail-under=60 --cov-report term-missing --cov=funAD > result.log)

      - name: check success or pass for test coverage
        run: (cd tests && ./check_coverage.sh pytest)

      # Run the test coverage for the build
      - name: Run tests and generate coverage html
        run: (cd tests && ./run_tests.sh pytest --cov=funAD --cov-report=html:htmlcov)

      # Remove .gitignore file in test coverage data to be pushed to gh-pages
      # branch
      - name: Clean .gitignore in coverage output
        run: rm -f tests/htmlcov/.gitignore

      # Deploy to gh-pages branch
      - name: Deploy test coverage GitHub page
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: tests/htmlcov


      

