name: test AD

# Controls when the workflow will run
on:
  push:
    branches:
      - milestone2_dev

# A workflow run is made up of one or more jobs that can run sequentially or in parallel.
# For more on jobs:
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobs
jobs:
  # Job ID
  install_and_test:

    name: unit test 01
    runs-on: ubuntu-latest
    steps:
      # Check out your repository under $GITHUB_WORKSPACE (job needs access to it)
      # See: https://github.com/actions/checkout
      - uses: actions/checkout@v3

      # Enable Python environment in your CI container
      # See: https://github.com/actions/setup-python
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10'  # let's use a recent version

      - name: Install dependencies
        run: python -m pip install pytest

      - name: Build and install the funAD in the container (using PEP517/518)
        run: (python -m build --wheel && python -m pip install dist/*)

      - name: Run tests using test harness
        run: (cd ./tests && chmod run_tests.sh 755 && ./run_tests.sh CI)

