name: test
on: [push]

jobs:
	install_and_test:
		runs-on: ubuntu-latest
		steps:
			- uses: actions/checkout@v3
			- uses: actions/setup-python@v3
			  with: 
					python-version: '3.10'
			- name: Install dependencies
				run: python -m pip install build pytest #shell command
			- name: Build and install the funAD in the container (using PEP517/518)
				run: (python -m build --wheel && python -m pip intall dist/*)
			- name: Run tests using test harness
				run: (cd tests && ./run_tests.sh CI)